#ifdef WHYIELD_COUNT

#if WHYIELD_COUNT == -1
#define WHYIELD_COUNT 0
WHCORO_LABLE_0 :
#elif WHYIELD_COUNT == 0
#define WHYIELD_COUNT 1
WHCORO_LABLE_1 :
#elif WHYIELD_COUNT == 1
#define WHYIELD_COUNT 2
WHCORO_LABLE_2 :
#elif WHYIELD_COUNT == 2
#define WHYIELD_COUNT 3
WHCORO_LABLE_3 :
#elif WHYIELD_COUNT == 3
#define WHYIELD_COUNT 4
WHCORO_LABLE_4 :
#elif WHYIELD_COUNT == 4
#define WHYIELD_COUNT 5
WHCORO_LABLE_5 :
#elif WHYIELD_COUNT == 5
#define WHYIELD_COUNT 6
WHCORO_LABLE_6 :
#elif WHYIELD_COUNT == 6
#define WHYIELD_COUNT 7
WHCORO_LABLE_7 :
#elif WHYIELD_COUNT == 7
#define WHYIELD_COUNT 8
WHCORO_LABLE_8 :
#elif WHYIELD_COUNT == 8
#define WHYIELD_COUNT 9
WHCORO_LABLE_9 :
#elif WHYIELD_COUNT == 9
#define WHYIELD_COUNT 10
WHCORO_LABLE_10 :
#elif WHYIELD_COUNT == 10
#define WHYIELD_COUNT 11
WHCORO_LABLE_11 :
#elif WHYIELD_COUNT == 11
#define WHYIELD_COUNT 12
WHCORO_LABLE_12 :
#elif WHYIELD_COUNT == 12
#define WHYIELD_COUNT 13
WHCORO_LABLE_13 :
#elif WHYIELD_COUNT == 13
#define WHYIELD_COUNT 14
WHCORO_LABLE_14 :
#elif WHYIELD_COUNT == 14
#define WHYIELD_COUNT 15
WHCORO_LABLE_15 :
#elif WHYIELD_COUNT == 15
#define WHYIELD_COUNT 16
WHCORO_LABLE_16 :
#elif WHYIELD_COUNT == 16
#define WHYIELD_COUNT 17
WHCORO_LABLE_17 :
#elif WHYIELD_COUNT == 17
#define WHYIELD_COUNT 18
WHCORO_LABLE_18 :
#elif WHYIELD_COUNT == 18
#define WHYIELD_COUNT 19
WHCORO_LABLE_19 :
#elif WHYIELD_COUNT == 19
#define WHYIELD_COUNT 20
WHCORO_LABLE_20 :
#elif WHYIELD_COUNT == 20
#define WHYIELD_COUNT 21
WHCORO_LABLE_21 :
#elif WHYIELD_COUNT == 21
#define WHYIELD_COUNT 22
WHCORO_LABLE_22 :
#elif WHYIELD_COUNT == 22
#define WHYIELD_COUNT 23
WHCORO_LABLE_23 :
#endif

#else
#error No Include WHCORO_BEGIN()
#endif